/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp6bis;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.sql.SQLException;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testFind() throws SQLException {

    Club club = new Club();
    club.setFabricant("ab1");
    club.setPoids(10.5);
    club.setId(1);
    EntityManagerImpl em = new EntityManagerImpl();
    Club trouve = em.<Club> find(Club.class, club.getId());
    assertEquals(club.getFabricant(), trouve.getFabricant());
    
    }
}
