/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tp6bis;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void testPersistence() {
        Club club = new Club();
        club.setFabricant("Fabricant1");
        club.setPoids(10.3);
        
        EntityManagerImpl em = new EntityManagerImpl();
        //em.persist(club);
    }
}
